# Generated by Django 2.1.1 on 2018-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_title', models.CharField(max_length=150)),
                ('channel_description', models.CharField(blank=True, max_length=500)),
                ('channel_link', models.URLField(max_length=1000)),
                ('channel_icon', models.URLField(blank=True, max_length=1000)),
            ],
        ),
    ]
