# Generated by Django 2.1.1 on 2018-09-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livetv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarJalsha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_name', models.CharField(max_length=100)),
                ('serial_link', models.URLField(max_length=1000)),
                ('timeStamp', models.DateField(auto_now_add=True)),
                ('activate', models.BooleanField(default=True)),
            ],
        ),
    ]
