# Generated by Django 2.1.1 on 2018-10-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livetv', '0002_starjalsha'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='mobile_compatibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='starjalsha',
            name='mobile_compatibility',
            field=models.BooleanField(default=True),
        ),
    ]
