# Generated by Django 2.1.1 on 2018-09-27 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_no', models.CharField(blank=True, max_length=12)),
                ('episode_title', models.CharField(blank=True, max_length=200)),
                ('episode_link', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=200)),
                ('series_season', models.CharField(blank=True, max_length=10)),
                ('series_icon', models.URLField(max_length=1000)),
                ('series_language', models.CharField(choices=[('1', 'English'), ('2', 'Hindi'), ('3', 'Bengali')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seriestv.Series'),
        ),
    ]
