# Generated by Django 2.1.1 on 2018-09-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriestv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='compatible',
            field=models.CharField(choices=[('1', 'Clappr'), ('2', 'YouTube'), ('3', 'OpenLoad')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_language',
            field=models.CharField(choices=[('1', 'English'), ('2', 'Hindi'), ('3', 'Bengali')], default='2', max_length=1),
        ),
    ]
