# Generated by Django 2.1.1 on 2018-09-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriestv', '0003_auto_20180927_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='compatible',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Clappr'), ('2', 'YouTube'), ('3', 'OpenLoad')], default='3', max_length=1),
        ),
    ]
