# Generated by Django 2.1.1 on 2018-10-05 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seriestv', '0006_auto_20181005_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seriestv.Series'),
        ),
    ]
