# Generated by Django 2.1.1 on 2018-10-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriestv', '0008_auto_20181005_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='mobile_compatibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='compatible',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Clappr'), ('2', 'YouTube'), ('3', 'OpenLoad'), ('4', 'RapidVideo')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_language',
            field=models.CharField(choices=[('1', 'English'), ('2', 'Hindi'), ('3', 'Bengali'), ('4', 'Other')], default='2', max_length=1),
        ),
    ]
