# Generated by Django 2.1.1 on 2018-10-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriestv', '0009_auto_20181009_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='compatible',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Clappr'), ('2', 'YouTube'), ('3', 'OpenLoad')], default='3', max_length=1),
        ),
    ]
