# Generated by Django 2.1.1 on 2018-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=150)),
                ('movie_trailer', models.URLField(max_length=1000)),
                ('movie_poster', models.URLField(max_length=1000)),
                ('movie_link', models.URLField(max_length=1000)),
            ],
        ),
    ]
