# Generated by Django 2.1.1 on 2018-09-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_genre',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_year',
            field=models.IntegerField(default=0),
        ),
    ]
