# Generated by Django 2.1.1 on 2018-09-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietv', '0002_auto_20180926_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_language',
            field=models.CharField(choices=[('1', 'English'), ('2', 'Hindi'), ('3', 'Bengali')], default='2', max_length=1),
        ),
    ]
