# Generated by Django 2.1.1 on 2018-09-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietv', '0003_movie_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='compatible',
            field=models.CharField(choices=[('1', 'Clappr'), ('2', 'YouTube'), ('3', 'OpenLoad')], default='1', max_length=1),
        ),
    ]
