# Generated by Django 2.1.1 on 2018-09-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietv', '0005_auto_20180927_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_link',
            field=models.CharField(max_length=1000),
        ),
    ]
