# Generated by Django 2.1.1 on 2018-10-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietv', '0007_auto_20180930_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mobile_compatibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_language',
            field=models.CharField(choices=[('1', 'English'), ('2', 'Hindi'), ('3', 'Bengali'), ('4', 'Other')], default='2', max_length=1),
        ),
    ]
